//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucaldas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APOYO_ECONOMICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APOYO_ECONOMICO()
        {
            this.DIRECTORIO_ARCHIVOS = new HashSet<DIRECTORIO_ARCHIVOS>();
        }
    
        public string ID_APOYO { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public int COSTO_INSCRIPCION { get; set; }
        public int COSTO_TRANSPORTE { get; set; }
        public int COSTO_ALOJAMIENTO { get; set; }
        public int COSTO_ALIMENTACION { get; set; }
        public int VALOR_SOLICITADO { get; set; }
        public string ID_EVENTO { get; set; }
        public decimal ID_ESTUDIANTE { get; set; }
        public string CONCEPTO_DIR_PROGRAMA { get; set; }
        public string CONCEPTO_DIR_LINEAINV { get; set; }
        public decimal ESTADO { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECTORIO_ARCHIVOS> DIRECTORIO_ARCHIVOS { get; set; }
        public virtual EVENTO EVENTO { get; set; }
    }
}
