//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucaldas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECTORIO_ARCHIVOS
    {
        public int ID_DIRECTORIO { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public string RUTA_SERVER { get; set; }
        public System.DateTime FECHA_SUBIDA { get; set; }
        public string ID_APOYO_ECONOMICO { get; set; }
        public decimal ESTADO { get; set; }
    
        public virtual APOYO_ECONOMICO APOYO_ECONOMICO { get; set; }
    }
}
