//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucaldas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTUDIANTE()
        {
            this.ACT_ACAD_ESTUDIANTE = new HashSet<ACT_ACAD_ESTUDIANTE>();
            this.APOYO_ECONOMICO = new HashSet<APOYO_ECONOMICO>();
            this.MONITORIA = new HashSet<MONITORIA>();
        }
    
        public decimal CODIGO { get; set; }
        public string ID_PERSONA { get; set; }
        public string SEMESTRE { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public decimal PROMEDIO_ACUMULADO { get; set; }
        public string ID_PROGRAMA { get; set; }
        public decimal ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACT_ACAD_ESTUDIANTE> ACT_ACAD_ESTUDIANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APOYO_ECONOMICO> APOYO_ECONOMICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONITORIA> MONITORIA { get; set; }
        public virtual PROGRAMA PROGRAMA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
