//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucaldas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACT_ACAD_ESTUDIANTE> ACT_ACAD_ESTUDIANTE { get; set; }
        public virtual DbSet<ACTIVIDAD_ACADEMICA> ACTIVIDAD_ACADEMICA { get; set; }
        public virtual DbSet<APOYO_ECONOMICO> APOYO_ECONOMICO { get; set; }
        public virtual DbSet<DIRECTORIO_ARCHIVOS> DIRECTORIO_ARCHIVOS { get; set; }
        public virtual DbSet<ESTUDIANTE> ESTUDIANTE { get; set; }
        public virtual DbSet<EVENTO> EVENTO { get; set; }
        public virtual DbSet<MONITORIA> MONITORIA { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PROGRAMA> PROGRAMA { get; set; }
        public virtual DbSet<TIPO_MONITORIA> TIPO_MONITORIA { get; set; }
    }
}
