//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucaldas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITORIA
    {
        public decimal ID_ESTUDIANTE { get; set; }
        public string PERIODO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ID_TIPO_MONITORIA { get; set; }
        public string ID_ACTIVIDAD_ACADM { get; set; }
        public decimal HORAS_REPORTADAS { get; set; }
        public decimal HORAS_PAGAS { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ESTADO { get; set; }
    
        public virtual ACTIVIDAD_ACADEMICA ACTIVIDAD_ACADEMICA { get; set; }
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual TIPO_MONITORIA TIPO_MONITORIA { get; set; }
    }
}
