//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ucaldas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROGRAMA()
        {
            this.ACTIVIDAD_ACADEMICA = new HashSet<ACTIVIDAD_ACADEMICA>();
            this.ESTUDIANTE = new HashSet<ESTUDIANTE>();
        }
    
        public string ID_PROGRAMA { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public decimal ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVIDAD_ACADEMICA> ACTIVIDAD_ACADEMICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTUDIANTE> ESTUDIANTE { get; set; }
    }
}
